//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmREST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public override string ToString()
        {
            return this.Login;
        }
        public int Id { get; set; }
        public string Post { get; set; }
        public string PhoneNumber { get; set; }
        public int Salary { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> CafeId { get; set; }
        public string FIO { get; set; }
    
        public virtual Cafe Cafe { get; set; }
    }
}
