//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmREST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public override string ToString()
        {
            return this.Name;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
        public int Price { get; set; }
        public int Calories { get; set; }
        public Nullable<int> CafeId { get; set; }
    
        public virtual Cafe Cafe { get; set; }
    }
}
